let data, plan, report;
const $ = id => document.getElementById(id);
function text(tag, value, cls) { const el=document.createElement(tag); el.textContent=value; if(cls) el.className=cls; return el; }
function invalidate(){plan=null;report=null;$('simulate').hidden=true;$('download').hidden=true;$('title').textContent='Know before you go.';$('result').replaceChildren(text('p','Selection changed. Review again.'));$('status').textContent='';}
function render(){ $('playlists').replaceChildren();data.playlists.forEach((p,i)=>{const row=text('div','','playlist');const input=document.createElement('input');input.type='checkbox';input.checked=true;input.id='pick-'+i;input.value=String(p.id??i);input.addEventListener('change',invalidate);const label=text('label',p.name);label.htmlFor=input.id;label.append(text('small',(p.tracks??p.track_uris??[]).length+' items'));row.append(input,label);$('playlists').append(row);});invalidate(); }
function payload(){return {data,destination:$('account').value,selected:[...document.querySelectorAll('#playlists input:checked')].map(x=>x.value)}}
async function call(path,body){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await res.json();if(!res.ok)throw Error(json.error);return json;}
$('account').addEventListener('change',invalidate);
$('file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Choose an export smaller than 2 MB.');const candidate=JSON.parse(await file.text());if(!Array.isArray(candidate.playlists)||candidate.playlists.some(p=>!p||typeof p.name!=='string'||!Array.isArray(p.tracks??p.track_uris??[])))throw Error('Export must contain named playlists and track arrays.');data=candidate;render();}catch(err){invalidate();$('status').textContent=err.message;}});
$('review').addEventListener('click',async()=>{invalidate();$('review').disabled=true;try{plan=await call('/api/review',payload());$('title').textContent='Your plan, made clear.';$('result').replaceChildren(text('p',plan.playlists.reduce((n,p)=>n+p.uris.length,0)+' items','metric'),text('p','Destination: '+plan.destination));plan.playlists.forEach(p=>$('result').append(text('p',p.name+'  |  '+p.uris.length+' items  |  private copy','summary')));$('result').append(text('p',plan.skipped.length+' skipped: local, unavailable or invalid items.','hint'));$('simulate').hidden=false;}catch(err){$('status').textContent=err.message;}finally{$('review').disabled=false;}});
$('simulate').addEventListener('click',async()=>{if(!plan)return;$('simulate').disabled=true;try{report=await call('/api/simulate',{...payload(),digest:plan.digest});$('title').textContent='Simulation complete.';$('result').replaceChildren(text('p','No Spotify playlists were changed.'));report.playlists.forEach(p=>$('result').append(text('p',p.name+'  |  '+p.added+'/'+p.total+' simulated  |  '+p.status,'summary')));$('simulate').hidden=true;$('download').hidden=false;}catch(err){$('status').textContent=err.message;}finally{$('simulate').disabled=false;}});
$('download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='passage-synthetic-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
fetch('/api/demo').then(r=>r.json()).then(d=>{data=d;render();}).catch(()=>{$('status').textContent='Unable to load demo. Restart the local studio.';});
